[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "argon2-cffi>=25.1.0",
    "click>=8.3.3",
    "fastapi>=0.136.1",
    "humanize>=4.16.0",
    "loguru>=0.7.3",
    "passlib[bcrypt]>=1.7.4",
    "pydantic>=2.13.4",
    "python-jose[cryptography]>=3.5.0",
    "python-json-logger>=4.1.0",
    "rich>=15.0.0",
    "sqlalchemy>=2.0.49",
    "tomli-w>=1.2.0",
    "uvicorn>=0.46.0",
]

[dependency-groups]
dev = [
    "factory-boy>=3.3.3",
    "freezegun>=1.5.5",
    "httpx>=0.28.1",
    "pdoc>=16.0.0",
    "pytest>=9.0.2",
]


[tool.pyright]
reportImportCycles = false
reportExplicitAny = false
reportUnannotatedClassAttribute = false
reportAny = false
reportIncompatibleVariableOverride = false
reportCallInDefaultInitializer = false
reportUnusedCallResult = false
reportImplicitStringConcatenation = false
reportUnnecessaryCast = false
reportUnnecessaryIsInstance = false

[tool.pytest.ini_options]
filterwarnings = [
    "ignore:Accessing argon2.__version__ is deprecated:DeprecationWarning:passlib"
]
# This somehow fixes tests
pythonpath = ["."]

# I'll use markers later mb
# markers = [
#     "slow: marks tests as slow",
#     "db: tests that use database",
# ]
