/* tslint:disable */
/* eslint-disable */
/**
 * TaskFuss API
 * API for TaskFuss app
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Standard API response wrapper
 * @export
 * @interface ApiResponse
 */
export interface ApiResponse {
    /**
     * 
     * @type {object}
     * @memberof ApiResponse
     */
    'data'?: object;
    /**
     * 
     * @type {string}
     * @memberof ApiResponse
     */
    'latency'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiResponse
     */
    'timestamp'?: string;
}

